### DISCUSSION TITLE
How to use other plugins with agent-stack-k8s

### DISCUSSION THREAD

**Discussion by jtoar** [buildkite/agent-stack-k8s#566] [Q&A]
Hey all, relatively new to Buildkite, using agent-stack-k8s and loving it so far.

Having some trouble getting the `aws-assume-role-with-web-identity` working. Here's an example of my setup:

```yaml
steps:
  - label: ":arrows_counterclockwise: E2E"
    command: ".buildkite/scripts/e2e-tests.sh"

    plugins:
      - kubernetes:
          podSpec:
            containers:
              - image: my-image-with-the-aws-cli
                env:
                  - name: BUILDKITE_PLUGIN_S3_CACHE_BUCKET
                    value: my-bucket

      - aws-assume-role-with-web-identity#v1.2.0:
          role-arn: arn:aws:iam::my-role

      - cache#v1.5.2:
          manifest: pnpm-lock.yaml
          backend: s3
          path: node_modules
          restore: file
          save: file
```

I've installed `aws` and `jq` in the base image and specified that base image in the `podSpec`, but the `aws-assume-role-with-web-identity` doesn't seem to be using that image. I get errors like the following:

<img width="798" alt="Screenshot 2025-04-15 at 12 02 57 PM" src="https://github.com/user-attachments/assets/407e3f83-87bf-4bc3-8a75-4b1a663487c2" />

I see these docs for hooks and plugins but not totally sure if they're related: https://github.com/buildkite/agent-stack-k8s/blob/main/docs/hooks_and_plugins.md.

Any help or guidance would be greatly appreciated—thanks!
