### ISSUE TITLE
Job does not get annotations from configuration

### ISSUE THREAD

**Issue by clbx** [buildkite/agent-stack-k8s#155]
Somewhere in the Build function in the scheduler, annotations that are passed in via the plugin configuration are being lost. 

For example I have a configuration of:

```yaml
name: "test pipeline"
agents:
   queue: kubernetes
plugins:
- kubernetes:
     metadata:
        annotations:
              example.com/annotation-test: "value"
     podSpec:
       containers:
       - name: app
          image: debian
          command: ["echo", "hello world"]
```
The resultant job will not have the annotation provided, but will have the buildkite build-url and job-url annotations

I think they're being overwritten somewhere in here:
https://github.com/buildkite/agent-stack-k8s/blob/b5811c8fbb21b4ab4c7869a775cc08454696cc2a/internal/scheduler/scheduler.go#L177-L186
