### ISSUE TITLE
Support externally created secrets

### ISSUE THREAD

**Issue by abhishekmukherg** [buildkite/agent-stack-k8s#167]
Currently, the agent-stack-k8s requires that the secret material for both `agentToken` and `graphqlToken` are provided to helm, for helm to templatize the data into a `Secret` object. This is incompatible with other secret management solutions like [External Secrets Operator](https://external-secrets.io/v0.8.1/). In these solutions, you would want to tell helm where to look for the secret and such, and allow the operator to create the actual Secret object. And very specifically for us, doing so would imply committing those rendered files to git, as we leverage a workflow as outlined in [Robbie's talk at Unblock a few year ago](https://www.youtube.com/watch?v=wPkHS4srJtY)

## Example

As an example for this workflow, you might have in your chart, that leverages `agent-stack-k8s` as a subchart, a template like

```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: template
spec:
  # ...
  target:
    name: my-secret
    creationPolicy: Owner
  data:
  - secretKey: agent-token
    remoteRef:
      key: /agent-token
```

The ESO will come in and fetch the secret from an external store (vault, AWS Secrets Manager) and create `my-secret` Secret from this `template` .

You could then reference it in a helm chart with

```yaml
secret:
  create: false
  existingSecret: my-secret
  agentTokenKey: agent-token
```

## Prior Art

This is effectively an ask to reproduce the work in https://github.com/buildkite/charts/pull/96 into the new chart

## Acceptance Criteria i.e. TLDR

Secrets for `agentToken` and `graphqlToken` can be specified via a combination of an externally created secret name, and a key within that Secret

**Comment by abhishekmukherg** [comment]
Note that this is an easy enough change to implement that I can do it, but wanted to get a ticket up as it's not obvious what the DSL should look like given the current values DSL. As in, what does this look like in the future:

```yaml
agentToken: foo
graphqlToken: bar
```

**Comment by triarius** [comment]
Thanks for bringing this up @abhishekmukherg, this is a much-needed improvement. We're happy for you to have a go at implementing this.

Perhaps the template can be flexible enough to check if `agentToken` and `graphqlToken` are strings or objects that reference ExternalSecrets. I think you should be able to put a giant if condition around `charts/agent-stack-k8s/templates/secrets.yaml.tpl` so that, in the later case, it is an empty YAML document.

**Comment by abhishekmukherg** [comment]
Just to get it on paper, I think you're suggesting

```yaml
agentToken: foo
# or
agentToken:
    externalSecretName: other
    externalSecretKey: key
```

and similarly

```yaml
graphqlToken: foo
# or
graphqlToken:
  externalSecretName: bar
  externalSecretKey: baz
```

I've not seen this pattern in other helm charts but it seems reasonable to me. Might be a bit finicky just to encode the logic in go template's DSL but can give it a crack
