### ISSUE TITLE
Jobs that ran into OOM issues appear as still running in buildkite UI

### ISSUE THREAD

**Issue by wallyqs** [buildkite/agent-stack-k8s#182]
For example, a `container-0` job ran into this OOM so it has already exited:

```
 - containerID: containerd://868661c9da807af9428729518d1c95a52c1bb5efac68df8799cd6b24b475125c
    image: docker.io/library/golang:1.20-alpine
    imageID: docker.io/library/golang@sha256:59fc0dc542a38bb5b94cd1529e5f4663b4e7cc2f4a6c352b826dafe00d820031
    lastState: {}
    name: container-0
    ready: false
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: containerd://868661c9da807af9428729518d1c95a52c1bb5efac68df8799cd6b24b475125c
        exitCode: 137
        finishedAt: "2023-07-14T10:40:18Z"
        reason: OOMKilled
        startedAt: "2023-07-14T10:31:49Z"
```

But in the buildkite UI it still appears running:

<img width="802" alt="image" src="https://github.com/buildkite/agent-stack-k8s/assets/26195/00a1e260-ce6c-498e-9376-5256cfb35d09">

Maybe need a way for the controller to detect OOM events in the jobs to clean them up?
