### ISSUE TITLE
[bug] global environment variables replace step level environment variables entirely

### ISSUE THREAD

**Issue by agates4** [buildkite/agent-stack-k8s#202]
If global environment variables are set in the top level pipeline file, it'll replace all of the step level env variables.

```yaml
env:
  myenv: "yes"

steps:
  - label: build image
    agents:
      queue: kubernetes
    plugins:
      - kubernetes:
          podSpec:
            containers:
              - image: alpine:latest
                command: [echo]
                env:
                  - name: DOCKER_HOST
                     value: tcp://localhost:2375
                args:
                - "Hello, world!"
```

In this example, the podSpec env will be totally replaced by the global environment variables. 
I propose the default behavior should be to merge them.

```yaml
                env:
                  - name: DOCKER_HOST
                     value: tcp://localhost:2375
                  - name: myenv
                     value: "yes"
```
