### ISSUE TITLE
[bug] artifacts dont upload on failed step

### ISSUE THREAD

**Issue by agates4** [buildkite/agent-stack-k8s#203]
```yaml
steps:
  - label: build image
    artifact_paths:
      - "myfile"
    agents:
      queue: kubernetes
    plugins:
      - kubernetes:
          podSpec:
            containers:
              - image: alpine:latest
                command: [echo]
                args:
                - false
                - exit 1
```
On completion, the entire pod is torn down, rather than exiting its own container and continuing to go into the artifact container
That means that no artifacts are uploaded
