### ISSUE TITLE
Plugins don't work for clusters backed by containerd runtime

### ISSUE THREAD

**Issue by dallbee** [buildkite/agent-stack-k8s#204]
Update: I now realize the issue I was experiencing was with the execution of another plugin, and not something agent-stack-k8s was doing.

Please close. Sorry for the trouble.

<details>

<summary>Original issue content</summary>
We're running into a roadblock attempting to migrate our workload to use the k8s agent stack.

Specifically, buildkite attempts to load the plugin by performing a docker pull, but there's no docker daemon since our kubernetes runtime is containerd.

Env:
```
Kubernetes Environment: Amazon EKS
Runtime: containerd
```

Error:
```
Found tag v1.11.0, pulling from docker hub
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Command failed with exit status: 1
Suppressing failure so pipeline can continue (if you do not want this behaviour, set fail_on_error to true)
```

pipeline config:
```
agents:
  queue: kubernetes

steps:
  - label: "example"
    artifact_paths: ["golangci-lint.xml"]
    plugins:
      - kubernetes:
          gitEnvFrom:
            - secretRef: { name: agent-stack-k8s }
          podSpec:
            containers:
              - image: ghcr.io/buildkite/agent-stack-k8s/agent:latest
                command: [bash]
                args:
                  - -ec
                  - "'echo test >> golangci-lint.xml'"
      - bugcrowd/test-summary#v1.11.0:
          inputs:
            - label: golangci-lint
              artifact_path: artifacts/golangci-lint.xml
              type: checkstyle
          formatter:
            type: details
          run_without_docker: true
```

What are our options here?
</details>
