### ISSUE TITLE
Plugin overwrites entrypoints

### ISSUE THREAD

**Issue by c2h5oh** [buildkite/agent-stack-k8s#223]
Kaniko image has entrypoint `/kaniko/executor`, see https://github.com/GoogleContainerTools/kaniko/blob/main/deploy/Dockerfile#L100

but:
```
- label: builder    
    plugins:
      - kubernetes:
          podSpec:
            containers:
              - image: gcr.io/kaniko-project/executor:debug
                args:
                  - "--context=/workspace/[...removed...]"
                  - "--dockerfile=Dockerfile"
                  - "--destination=my-image"
```
gets me:
```
trap 'kill -- $$' INT TERM QUIT; --context=/workspace/[...removed...] --dockerfile=Dockerfile --destination=my-image
/bin/sh: --context=/workspace/[...removed...]: not found
```

this works:
```
- label: builder    
    plugins:
      - kubernetes:
          podSpec:
            containers:
              - image: gcr.io/kaniko-project/executor:debug
                command: [/kaniko/executor]
                args:
                  - "--context=/workspace/[...removed...]"
                  - "--dockerfile=Dockerfile"
                  - "--destination=my-image"
```

Again, this should at the very least be documented.
