### ISSUE TITLE
"failure" job uses private image causing imagePullBackoff

### ISSUE THREAD

**Issue by bpoland** [buildkite/agent-stack-k8s#273]
Hey, I'm running into a bug consistently but it's pretty weird :)

In my podspec I am using an `imagePullSecrets` section since I'm using a private image.  It looks something like this (I've removed some extra sections that don't seem relevant, but let me know if you can't reproduce and I can share more details):

```
  - label: Build
    plugins:
      - kubernetes:
          gitEnvFrom:
            - secretRef:
                name: buildkite-agent-ssh
          podSpec:
            imagePullSecrets:
              - name: image-pull-secret
            containers:
              - image: <my-private-image>
                command:
                  - |
                    echo "+++ build"
                    <my build command>
            volumes:
              - name: agent-hooks
                configMap:
                  name: buildkite-agent-hooks
                  defaultMode: 0755
          extraVolumeMounts:
            - name: agent-hooks
              mountPath: /buildkite/hooks
```

This worked fine and created a pod with the correct imagePullSecrets. But, we use a yaml linter that told me to replace the `defaultMode: 0755` with `defaultMode: "0755"` and when I did that, the pod created by agent-stack-k8s was now missing the `imagePullSecrets` and it failed to pull the image :(

I don't understand why adding quotes would have broken this but hopefully you can reproduce and fix it! :)
