### ISSUE TITLE
Hooks don't work when checkout is skipped

### ISSUE THREAD

**Issue by bpoland** [buildkite/agent-stack-k8s#314]
Hey, I noticed that when we try disabling checkout (https://github.com/buildkite/agent-stack-k8s/pull/303) that our `environment` hooks don't run (the `pre-checkout` hook also doesn't run but I'd expect that :) )

Maybe the environment hooks normally get run on the checkout container which is no longer present when checkout is disabled?

potentially related issues:
- https://github.com/buildkite/agent-stack-k8s/issues/227
- https://github.com/buildkite/agent-stack-k8s/issues/239
- https://github.com/buildkite/agent-stack-k8s/pull/258

**Comment by DrJosh9000** [comment]
Hi @bpoland, that's kind of weird! It was working before?

I had a quick look in the agent and couldn't see a reason the `environment` hook wouldn't still be run in the command container(s). It's part of [`setUp`](https://github.com/buildkite/agent/blob/3de030e6792e13cac4f7e10ff0527537627a664d/internal/job/executor.go#L765) which isn't conditional on any phases.

**Comment by bpoland** [comment]
> Hi @bpoland, that's kind of weird! It was working before?
> 
> I had a quick look in the agent and couldn't see a reason the `environment` hook wouldn't still be run in the command container(s). It's part of [`setUp`](https://github.com/buildkite/agent/blob/3de030e6792e13cac4f7e10ff0527537627a664d/internal/job/executor.go#L765) which isn't conditional on any phases.

Hey, yep I tried removing the `kubernetes.skip.checkout: true` and then the hooks run again, although I think likely on the checkout container? (hard to tell from the Buildkite UI which container it is).

Is the environment hook supposed to run on both the checkout container and the command container separately?  With checkout enabled I only see it running once.

**Comment by DrJosh9000** [comment]
Yeah, as far as I can tell if both containers are enabled, and the environment hook is present in both, and the hooks env var is configured, then the environment hook should still get run twice.

**Comment by DrJosh9000** [comment]
I couldn't replicate, but I'll paste my notes here and we can compare 🧑🏻‍💻

As setup, I have a directory of trivial `testhooks` containing most job lifecycle hooks except `checkout` and `command`. For testing purposes I'm mounting them using [`hostPath`](https://kubernetes.io/docs/concepts/storage/volumes/#hostpath).

Here's a pipeline which skips checkout:

```yaml
agents:
  queue: kubernetes
steps:
  - label: "hook time"
    command:
      - echo $$BUILDKITE_HOOKS_PATH
      - ls /buildkite/hooks
    plugins:
      - kubernetes:
          checkout:
            skip: true
          podSpecPatch:
            containers:
              - name: "container-0"
                image: ghcr.io/buildkite/agent:latest
                env:
                  - name: BUILDKITE_HOOKS_PATH
                    value: /buildkite/hooks
            volumes:
              - name: agent-hooks
                hostPath:
                  path: /Users/josh/testhooks
                defaultMode: 0755
          extraVolumeMounts:
            - name: agent-hooks
              mountPath: /buildkite/hooks
              readOnly: true
```

It ran the environment, pre-command, post-command, and pre-exit hooks:

```plain
Running global environment hook
Running global pre-command hook
Running commands
$ echo $BUILDKITE_HOOKS_PATH
ls /buildkite/hooks
/buildkite/hooks
environment    post-checkout  pre-artifact   pre-checkout   pre-exit
post-artifact  post-command   pre-bootstrap  pre-command
Running global post-command hook
Running global pre-exit hook
```

I ran the same pipeline with `checkout: skip: true` commented out and another container podSpecPatch for "checkout":

```yaml
...
      - kubernetes:
          # checkout:
          #   skip: true
          podSpecPatch:
            containers:
...
              - name: "checkout"
                image: ghcr.io/buildkite/agent:latest
                env:
                  - name: BUILDKITE_HOOKS_PATH
                    value: /buildkite/hooks
...
```

and it ran environment, pre-checkout, post-checkout, environment (again), pre-command, post-command, and pre-exit hooks:

```plain
Running global environment hook
Running global pre-checkout hook
Preparing working directory
Running global post-checkout hook
Running global environment hook
Running global pre-command hook
Running commands
$ echo $BUILDKITE_HOOKS_PATH
ls /buildkite/hooks
/buildkite/hooks
environment    post-checkout  pre-artifact   pre-checkout   pre-exit
post-artifact  post-command   pre-bootstrap  pre-command
Running global post-command hook
Running global pre-exit hook
```
