### ISSUE TITLE
Can't use non-root user with podSpecPatch

### ISSUE THREAD

**Issue by bpoland** [buildkite/agent-stack-k8s#326]
Hi, I'm trying to use the new functionality introduced with https://github.com/buildkite/agent-stack-k8s/pull/282 but running into some issues with checkout.  I was initially seeing the checkout container error at startup with this message logged:
```
mkdir: can't create directory '//.ssh': Permission denied
```
I compared the resulting pod spec from before and after and noticed that previously [this logic](https://github.com/buildkite/agent-stack-k8s/blob/main/internal/controller/scheduler/scheduler.go#L582) seems to have been triggered to create a non-root user and it looks like that's no longer happening when using podSpecPatch.

I tried manually adding the root `securityContext` in my podSpecPatch but that causes other permissions errors after checkout, since it's trying to run as a non-root user later.  It seems like the above linked logic needs to be triggered even when using podSpecPatch?

**Comment by moskyb** [comment]
yo! @DrJosh9000 is gonna take a look at this for you, will get back to you soon.

**Comment by DrJosh9000** [comment]
I'm not sure I understand exactly how this is falling down, but I'll post my debugging so far anyway. Quick recap - the scheduler does this:

1. Initialise a `podSpec` using the one from the `kubernetes` "plugin", or a default that runs `command`
2. ...a variety of unrelated(?) nonsense...
3. Adds on the other containers, including `checkout` if enabled...
   - ...which inspects the `securityContext` in the `podSpec` so far. Based on whether `runAsUser` and `runAsGroup` are nonzero, it runs the extra logic to create the user/group in the checkout container before checking out
4. ...more unrelated nonsense (the init container)...
5. Apply `podSpecPatch` from config (helm values), then from the "plugin"

So, if the `securityContext` is supplied by `podSpecPatch` and not by `podSpec`, it won't be seen by `createCheckoutContainer`, so that logic won't be run.

Here's a pipeline that ran for me:

```yaml
agents:
  queue: kubernetes
steps:
  - label: ":pipeline:"
    plugins:
      - kubernetes:
          podSpec:
            securityContext:
              runAsUser: 2000
              runAsGroup: 2000
            containers:
              - name: "command"
                image: "alpine:latest"
                command: ["ash -c"]
                args: ["'whoami ; id ; ls -l'"]
          podSpecPatch:
            containers:
              - name: "checkout"
```

which worked:

```plain
~~~ Preparing working directory
...snip...
~~~ Running commands 
$ ash -c 'whoami ; id ; ls -l'
whoami: unknown uid 2000
uid=2000 gid=2000 groups=2000
total 4
-rw-r--r--    1 2000     2000            32 May 22 06:01 README.md
```

But I guess that's not ideal - you have to go back to specifying a bunch of things in `podSpec`, bringing back a bunch of the pipeline duplication.

My off-the-top-of-my-head solution would be: instead of conditioning the user/group creation logic on what the security context is at schedule time, the checkout container could compare current and intended UID/GID at run time. (Perhaps the command container should be doing the same thing.)
