### ISSUE TITLE
Following the installation instructions and testing the simple example in the readme fails in imagecheck-0 step

### ISSUE THREAD

**Issue by aressem** [buildkite/agent-stack-k8s#498]
Installing the v0.22.0 version of the stack using the helm chart completes successfully and the controller pod is running.  Creating a pipeline with the example in the readme fails.

Example used:
```
steps:
- label: Hello World!
  agents:
    queue: kubernetes
  plugins:
  - kubernetes:
      podSpec:
        containers:
        - image: alpine:latest
          command:
          - echo Hello World!
 ``` 

Error observed:
```
Warning  Failed            4s    kubelet            Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: exec: "/workspace/tini-static": stat /workspace/tini-static: no such file or directory: unknown
```

To me it seems like the `imagecheck-0` container picks up the alpine image that does not have the `tini-static` binary:
```
Init Containers:
  imagecheck-0:
    Container ID:  containerd://8259ee370a235ee7e1a9ecac2dfac7b0264399e1dc8e68696ab0152e245ae560
    Image:         alpine:latest
    Image ID:      alpine@sha256:56fa17d2a7e7f168a043a2712e63aed1f8543aeafdcee47c58dcffe38ed51099
    Port:          <none>
    Host Port:     <none>
    Command:
      /workspace/tini-static
    Args:
      --version
    State:          Terminated
      Reason:       StartError
      Message:      failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: exec: "/workspace/tini-static": stat /workspace/tini-static: no such file or directory: unknown
      Exit Code:    128
      Started:      Thu, 01 Jan 1970 01:00:00 +0100
      Finished:     Thu, 06 Feb 2025 23:55:32 +0100
```

So have I misunderstood something here or is the example just not working anymore?
