### ISSUE TITLE
git-lfs support?

### ISSUE THREAD

**Issue by NorthIsUp** [buildkite/agent-stack-k8s#553]
I'm trying to figure out how to get git lfs files pulled when cloning/pulling the repo. is there any documentation or examples of how people are doing this?

**Comment by petetomasik** [comment]
Hi @NorthIsUp! 👋 

Are you using an image for the `checkout` container that has [Git LFS](https://git-lfs.com/) installed? The default image used for containers is `buildkite/agent:latest`, which does not include Git LFS.

**Comment by NorthIsUp** [comment]
No, and I couldn't figure out how to specify it. more comprehensive documentation would be super helpful.

I ended up fixing it by writing a plugin that installs it before the checkout step.

https://github.com/NorthIsUp/git-lfs-buildkite-plugin/blob/master/hooks/pre-checkout

Maybe consider this a feature request to add git-lfs to the default image? The only references to git-lfs in the buildkite docs implied that it should be there: https://buildkite.com/docs/pipelines/hosted-agents/linux#agent-images

**Comment by petetomasik** [comment]
A [custom image](https://github.com/buildkite/agent-stack-k8s/blob/main/docs/podspec.md#custom-images) for the `checkout` container would be defined either by `podSpec` or `podSpecPatch`, depending on your job's requirements.
Example:
```
agents:
  queue: kubernetes
steps:
- commands:
  - echo hello world
  plugins:
  - kubernetes:
      podSpecPatch:
      - name: checkout
        image: my-repo/my-custom-git-lfs-checkout-image
```
Using a `pre-checkout` hook is also a viable option for pre-installing `git-lfs` ahead of `checkout`. We'll evaluate adding `git-lfs` to the `buildkite/agent` container image.
