### ISSUE TITLE
[BUG] Hooks are not automatically mounted inside command and checkout containers

### ISSUE THREAD

**Issue by RemcodM** [buildkite/agent-stack-k8s#617]
## Describe the bug
According to https://buildkite.com/docs/agent/v3/agent-stack-k8s/setting-up-hooks-and-plugins, setting up agent hooks should be as simple as setting up a `hooksVolume` in de `agent-config` of `values.yaml`. Sadly, this does not entirely work as advertised.

Specifically, the documentation mentions:
> If used, the corresponding volumes named buildkite-hooks and buildkite-plugins will be automatically mounted on checkout and command containers, with the Buildkite Agent configured to use them.

However, this does not appear to be the case. Once `hooksVolume` is set-up, it is in fact added as a volume to the `PodSpec` and a volume mount is created in the `agent` container, however, for the command and checkout container, no volume mount is created automatically and no environment variable `BUILDKITE_HOOKS_PATH` is set either, causing hooks not to run as advertised per documentation.

## To Reproduce
1. Deploy with a `hooksVolume`, e.g.:
```yaml
config:
  agent-config:
    hooksVolume:
      name: buildkite-hooks
      configMap:
        defaultMode: 493  # 755
        name: some-buildkite-hooks-configmap
```

2. Run a simple command inside a job on the Kubernetes cluster. No Kubernetes plug-in required:
```yaml
- name: ":buildkite:"
  command: bin/some_command
```

3. See that the scheduled job correctly creates the volume inside the PodSpec and mounts it in the `agent` container, but not the `checkout` or `container-0`.

## Expected behavior
Based on the documentation, I expect `volumeMount`s to be automatically created for the `checkout` and `container-0` containers. I furthermore expect the `BUILDKITE_HOOKS_PATH` environment variable to be set automatically and correctly.

## Environment
- agent-stack-k8s version: `0.28.0`
- Kubernetes version: `1.33.1`
- Deployment method: Helm chart

## Logs
N/A

## Additional context
Based on the source code of the controller, I believe the hookVolume is only mounted here https://github.com/buildkite/agent-stack-k8s/blob/main/internal/controller/config/agent_config.go#L107-L117, but that is indeed only applied to the `agent` container. Something like `ApplyToCommand` does not contain this: https://github.com/buildkite/agent-stack-k8s/blob/main/internal/controller/config/agent_config.go#L174-L189

As a user, I can workaround this bug by manually providing `extraVolumeMounts` through the Kubernetes plugin. By using the volume already added to the podspec and setting the `BUILDKITE_HOOKS_PATH` environment variable, I can get hooks to work correctly:
```
- name: ":buildkite:"
  command: bin/some_command
  env:
    BUILDKITE_HOOKS_PATH: /buildkite/hooks
  kubernetes:
    extraVolumeMounts:
      - mountPath: /buildkite/hooks
        name: buildkite-hooks
```

Furthermore, based on the source code, I expect exactly the same problem to be present for the plugins volume, however, I have not tested that in detail, since I had no particular need for it in our use case.
